name: grock
description: A flutter extension project.
version: 0.0.2+6
# author: Ahmet Ã–zberk <ahmet.ozberk.mrs@gmail.com>
homepage: https://github.com/ahmet-ozberk/grock

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^1.3.0
  page_transition: ^2.0.5
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
